-- MySQL Script generated by MySQL Workbench
-- Thu Aug  7 15:15:45 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema animaltrack
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `animaltrack` ;

-- -----------------------------------------------------
-- Schema animaltrack
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `animaltrack` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `animaltrack` ;

-- -----------------------------------------------------
-- Table `animaltrack`.`protectoras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `animaltrack`.`protectoras` (
  `idprotectoras` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `cif` VARCHAR(45) NULL DEFAULT NULL,
  `ubicacion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idprotectoras`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `animaltrack`.`animal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `animaltrack`.`animal` (
  `idanimal` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `chip` VARCHAR(45) NULL DEFAULT NULL,
  `especie` VARCHAR(45) NULL DEFAULT NULL,
  `fecha_esterilizacion` DATETIME NULL DEFAULT NULL,
  `foto` LONGTEXT NULL DEFAULT NULL,
  `lugar` VARCHAR(45) NULL DEFAULT NULL,
  `enfermedades` VARCHAR(45) NULL DEFAULT NULL,
  `protectoras_idprotectoras` INT NOT NULL,
  PRIMARY KEY (`idanimal`),
  INDEX `fk_animal_protectoras1_idx` (`protectoras_idprotectoras` ASC) VISIBLE,
  CONSTRAINT `fk_animal_protectoras1`
    FOREIGN KEY (`protectoras_idprotectoras`)
    REFERENCES `animaltrack`.`protectoras` (`idprotectoras`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `animaltrack`.`enfermedades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `animaltrack`.`enfermedades` (
  `idenfermedades` INT NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `sintomas` VARCHAR(45) NULL DEFAULT NULL,
  `tratamiento` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idenfermedades`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `animaltrack`.`enfermedades_has_animal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `animaltrack`.`enfermedades_has_animal` (
  `enfermedades_idenfermedades` INT NOT NULL,
  `animal_idanimal` INT NOT NULL,
  PRIMARY KEY (`enfermedades_idenfermedades`, `animal_idanimal`),
  INDEX `fk_enfermedades_has_animal_animal1_idx` (`animal_idanimal` ASC) VISIBLE,
  INDEX `fk_enfermedades_has_animal_enfermedades1_idx` (`enfermedades_idenfermedades` ASC) VISIBLE,
  CONSTRAINT `fk_enfermedades_has_animal_animal1`
    FOREIGN KEY (`animal_idanimal`)
    REFERENCES `animaltrack`.`animal` (`idanimal`),
  CONSTRAINT `fk_enfermedades_has_animal_enfermedades1`
    FOREIGN KEY (`enfermedades_idenfermedades`)
    REFERENCES `animaltrack`.`enfermedades` (`idenfermedades`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `animaltrack`.`voluntarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `animaltrack`.`voluntarios` (
  `idvoluntarios` INT NOT NULL,
  `dni` VARCHAR(45) NULL DEFAULT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `apellidos` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idvoluntarios`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `animaltrack`.`protectoras_has_voluntarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `animaltrack`.`protectoras_has_voluntarios` (
  `protectoras_idprotectoras` INT NOT NULL,
  `voluntarios_idvoluntarios` INT NOT NULL,
  PRIMARY KEY (`protectoras_idprotectoras`, `voluntarios_idvoluntarios`),
  INDEX `fk_protectoras_has_voluntarios_voluntarios1_idx` (`voluntarios_idvoluntarios` ASC) VISIBLE,
  INDEX `fk_protectoras_has_voluntarios_protectoras_idx` (`protectoras_idprotectoras` ASC) VISIBLE,
  CONSTRAINT `fk_protectoras_has_voluntarios_protectoras`
    FOREIGN KEY (`protectoras_idprotectoras`)
    REFERENCES `animaltrack`.`protectoras` (`idprotectoras`),
  CONSTRAINT `fk_protectoras_has_voluntarios_voluntarios1`
    FOREIGN KEY (`voluntarios_idvoluntarios`)
    REFERENCES `animaltrack`.`voluntarios` (`idvoluntarios`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `animaltrack`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `animaltrack`.`usuarios` (
  `idusuarios` INT NOT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  `user` VARCHAR(45) NULL DEFAULT NULL,
  `voluntarios_idvoluntarios` INT NOT NULL,
  PRIMARY KEY (`idusuarios`, `voluntarios_idvoluntarios`),
  INDEX `fk_usuarios_voluntarios1_idx` (`voluntarios_idvoluntarios` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_voluntarios1`
    FOREIGN KEY (`voluntarios_idvoluntarios`)
    REFERENCES `animaltrack`.`voluntarios` (`idvoluntarios`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
